simonlindholm/decomp-permuter

randomizer.py

This occurs if the only declaration is the function declaration

Fix infinite loop in decl randomizer

---

main.py
perm/perm_eval.py
randomizer.py

Use dependency injection for the random object.
This is in preparation for multi-threading so each thread can get its own random class and concurrency issues.

Dependency inject random

---

src/ast_util.py
src/perm/perm.py
src/randomizer.py

Allows compiler-specific pragmas like `#pragma intrinsic(fabsf)`

Only ignore permuter-specific pragmas

---

src/objdump.py

this fixes objdump not disassembling some opcodes (such as daddu) and just leaving them as hex

objdump: disassemble specifically for R4300

---

src/ast_util.py
src/randomizer.py

doesn't handle declarations that are in other blocks

Place new_var declarations in random positions

---

src/scorer.py

The original scoring used a set to record any commonalities between the insertion and deletion lists, when considering the reordering penalty. Later, when checking to see if an insertion or deletion was considered a reordering, it (erroneously) checked if the opcode from the common set was in the list of insertions or deletions. This fails to take into account the case where two of the same opcode was inserted or deleted, but only one should be considered a case of reordering. The new code removes only the number of occurrences common between the two lists; e.g. if insertions has 5 and deletions has 4, 4 of the item is removed from both insertions and deletions.
In order to account for reorderings, num_common*PENALTY_REORDERING is added to the score. This correctly accounts for …

fix insertion/deletion penalty bug in scorer.py

---

import.py

Adds two new `permuter_settings.toml` options for skipping the 'figure out the compile command via Make/Ninja' process.
e.g. on https://github.com/pmret/papermario:
```toml
compiler_command = "cpp -Iinclude -Isrc -D _LANGUAGE_C -D _FINALROM -ffreestanding -DF3DEX_GBI_2 -D_MIPS_SZLONG=32  -D SCRIPT(...)={} | iconv --from UTF-8 --to SHIFT-JIS | tools/linux/cc1 -O2 -quiet -G 0 -mcpu=vr4300 -mfix4300 -mips3 -mgp32 -mfp32 -Wuninitialized -Wshadow  -o - | tools/linux/mips-nintendo-nu64-as -EB -G 0 -"
assembler_command = "mips-linux-gnu-as -march=vr4300 -mabi=32"
```

add compiler_command/assembler_command settings

---

src/permuter.py

Please consider this PR.
A common workflow with mwcc ppc projects is having a very large context that is copied across scratches that often times has several inlines and nested inlines, these count as functions making therefore more than one function in the file, and the function name must be specified function.txt, but that is another step which makes slows down work flow.  Adding this PR would save time and make it easier to use by just defaulting to the last function in the file.  (since inlines are typically above in context)
So with this PR, you can still specify a function with that txt file, but in the case where its not specified and there are more than one function, it will just default to choosing the last (bottom) function.

default to selecting the last function in file when there is more than one

---

src/main.py

Often times context is thousands of lines long (atleast for decomp projects I am involved in) and it is a pain to scroll down all the time to view the function of interest at the bottom, and also lots of unnecessary disk usage.
This simply finds the first instance of the function name and then only saves text after that point.

trim source output to only show the target function code and below

---

src/ast_util.py

keep functions marked as inline in the Candidate ast, thus remaining in the Candidate source.

keep functions marked as inline in the candidate source

---

src/ast_util.py

tweak to prunt_ast: so it strips out inline functions defs that are not used by target function, but keeps ones that are used

tweak to prunt_ast

---

default_weights.toml

It'd be nice to have some GCC users look over the passes and make sure I didn't miss any or include one here that shouldn't have been.

Change weights for ido passes to 0.5 when using gcc

---

import.py

any thoughts / objections? is there a better way to do this? psx assembler is not a fan of macros :(

Allow .globl as function label prefix

---

src/objdump.py

hopefully prevents bugs like this from surfacing in the future
not sure if explicitly checking for "nop" is arch agnostic enough, but also not sure if that's worth addressing here

remove trailing nops from objdump output

---

import.py

Hi there! Thanks for making decomp-permuter, I've found it immensely helpful.
I'd like to leverage `import.py` for use in my own project. Specifically, I'm trying to make a Python script that will automate most of the process of creating a decomp.me page from raw Assembly. This includes things like putting rodata into the .asm file prior to the initial decompilation. In order to create the decomp.me page, I'm currently doing:
```
import_string = f'tools/decomp-permuter/import.py {c_filename} {asm_filename} --decompme'
print(f"Calling {import_string}")
os.system(import_string)
```
But this calling out to the OS seems a little clumsy. It would be nice if I could call import.py from within Python itself, by importing import.py and then calling its `main()` function. However, since `main()` …

Allow passing arguments to main() from external source

---

import.py

A change introduced in https://github.com/decompme/decomp.me/pull/945
It's no longer possible to claim a scratch without a token. This new endpoint will automatically claim the scratch when visited.

decomp.me: Use new scratch claim token

---

README.md
src/main.py
src/net/client.py
src/net/core.py
src/net/evaluator.py
src/scorer.py

#67
I have tested the local version of these changes, don't know if I got the permuter@home related stuff correct or not.
Cribs very, very heavily off simonlindholm/asm-differ@846a069
Leaves difflib as the default
Motivated by a unique circumstance in the MK64 decomp where the difflib and Levenshtein algorithms disagree ever so slightly, which made it hard to interpret the permuter's output when comparing it to asm-differ's.

 #67 Add Levenshtein as a diff algorithm option

---

import.py

The default prelude.inc assumes MIPS. I'm not sure if there's already a way to turn that off, but having a project-wide setting seems useful

Add asm_prelude_file setting for import.py

---

src/main.py
src/permuter.py

The goal here is just that I don't want (or need) the permuter to run at max speed and taking my CPU up to max temperatures for minutes at a time, so I wanted a way to reduce the speed of execution and make it more idle friendly.
This is almost certainly not the best way to do this, so feel free to replace this with a nicer/better version, I just wanted to get *something* working.

Implement a basic speed setting to reduce the resources spent on permuting

---

import.py

decomp-permuter can extract compiler flags that aren't necessary or even valid on decomp.me, so the flags should be overridable.

Add settings flag to specify decomp.me compiler flags

---

prelude.inc

splat/spimdisasm added new labels on the generated assembly and changed a few defaults too (https://github.com/ethteck/splat/pull/466), breaking importing assembly to decomp-permuter.
This PR updates the labels and adds new ones to the prelude.inc file, fixing the import issue.

Update labels for better support with latest splat/spimdisasm

---

import.py

We're trying to deprecate and remove the /compilers endpoint, and /compiler is the new one-stop shop for all your compiler metadata needs.

Use new endpoint for compilers on decomp.me
