- src/randomizer.py
> Add mask perm to randomizer

- src/ast_types.py
- src/randomizer.py
> Add perm_cast_simple

- .gitignore
- src/scorer.py
> %lo / %hi should match any literal

- src/main.py
Best score and tied best are green, better score and different asm same score are orangy-yellow.
> Terminal colors

- src/randomizer.py
Not sure how this will handle for loops, assignments inside expressions, etc.
> Add perm_split_assignment

- import.py
There are probably more pythonic ways to do what I've done here, so I'm open to any suggestions if you'd like something to be written differently.
> Modified compile command generation for PM support

- src/randomizer.py
randomizes floating point literals
0.x -> .x
x.0 -> x.
using or not using f to indicate float
> add float literal randomization

- src/randomizer.py
Some notes:
* I'm not in love with the name I picked. Let me know if you think it should change.
* I gave the weight for it `5` - not sure if that should change
> Added perm_equals_operator pass

- src/main.py
> Add --best-only

- src/randomizer.py
Since I've seen regalloc cycle with 3 or 4 masks, I just chose 12 arbitrarily since 12 has a lot of factors.
> Sometimes add multiple masks in perm_add_mask

- src/scorer.py
> bug fix in parsing and scoring ppc objdump

- src/objdump.py
for loading external data with lfs and probably more.
> init attempt to fix r2 reloc for ppc, 

- src/main.py
- src/net/evaluator.py
- src/permuter.py
pretty simple, not too much to say.  code is pretty self explanatory
> add feature flag to add minimum score threshold

- src/objdump.py
- src/scorer.py
Also does various other refactoring and possible fixes outside of ppc too.
This matches the latest design decisions from asm-differ PR # 84
I am closing the previous PR, that this is build off of
> PPC reloc fixes

- import.py
- src/compiler.py
- src/helpers.py
- src/main.py
- src/net/evaluator.py
- src/objdump.py
- src/permuter.py
- src/scorer.py
add debug mode to latest main branch
> add debug mode

- test/test_perm.py
> Oops, fixing the tests

- src/randomizer.py
I plan to keep working on this some more and features related to it.
But right now it seems to be working and tests are passing, so up to you if you want to work on merging into main now, or wait.  Doesn't matter much to me for this PR.
> add perm_chain_assignment randomization

- src/ast_types.py
remove fn_ret_types
and case where expr is ID inside of FuncCall in expr_type
fixes glitch with function calls from function pointers
> remove fn_ret_types

- src/ast_util.py
> mypy fix for PR #132

- src/randomizer.py
tweak creating the replace cand set to have more possible options
> tweak creating the replace cand set to have more possible options

- src/randomizer.py
expand perm_chain_assignment, adding a chance to create the chain assignment with a non consecutive statement
> expand perm_chain_assignment, adding a chance to create the chain assignment with a non consecutive statement

- default_weights.toml
- src/randomizer.py
Create a long chain assignment out of 3 or more consecutive assignments with equal rvalue
> perm_long_chain_assignment

- default_weights.toml
- src/ast_util.py
- src/candidate.py
- src/randomizer.py
- stubs/pycparser/c_ast.py
WIP - sharing what I got so far
> Perm inline get structmember

- README.md
- src/main.py
- src/net/core.py
alternate solution for supporting windows or systems without pynacl
Let me know what changes you would like or additions, 
then if this works I will close the other PR
> alternate solution for supporting windows or systems without pynacl
